fix: Only attempt to install vllm on linux
I'm getting errors when trying to install vllm 0.9.1 on macos (reproduced below).

Like unsloth, we should only attempt to install vllm on linux.

```
  × Failed to build `outlines-core==0.1.26`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_py
      copying python/outlines_core/_version.py ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core
      copying python/outlines_core/__init__.py ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core
      running egg_info
      writing python/outlines_core.egg-info/PKG-INFO
      writing dependency_links to python/outlines_core.egg-info/dependency_links.txt
      writing requirements to python/outlines_core.egg-info/requires.txt
      writing top-level names to python/outlines_core.egg-info/top_level.txt
      reading manifest file 'python/outlines_core.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'python/outlines_core.egg-info/SOURCES.txt'
      copying python/outlines_core/py.typed ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core
      copying python/outlines_core/fsm/__init__.py ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core/fsm
      copying python/outlines_core/fsm/guide.py ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core/fsm
      copying python/outlines_core/fsm/json_schema.py ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core/fsm
      copying python/outlines_core/fsm/outlines_core_rs.pyi ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core/fsm
      copying python/outlines_core/fsm/regex.py ->
      build/lib.macosx-14.0-arm64-cpython-313/outlines_core/fsm
      running build_ext
      running build_rust

      [stderr]
      /Users/kyle/Library/Caches/uv/builds-v0/.tmp8FbUtL/lib/python3.13/site-packages/setuptools/config/_apply_pyprojecttoml.py:82:
      SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
      !!

              ********************************************************************************
              Please use a simple string containing a SPDX expression for `project.license`. You
      can also use `project.license-files`. (Both options available on setuptools>=77.0.0).

              By 2026-Feb-18, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license
      for details.
              ********************************************************************************

      !!
        corresp(dist, value, root_dir)
      ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't
      any
      /Users/kyle/Library/Caches/uv/builds-v0/.tmp8FbUtL/lib/python3.13/site-packages/setuptools/command/build_py.py:212:
      _Warning: Package 'outlines_core.fsm' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'outlines_core.fsm' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'outlines_core.fsm' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'outlines_core.fsm' to be distributed and are
              already explicitly excluding 'outlines_core.fsm' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      cargo rustc --lib --message-format=json-render-diagnostics --manifest-path
      Cargo.toml --release -v --features pyo3/extension-module python-bindings
      --crate-type cdylib -- --crate-type=cdylib -C link-args=-undefined dynamic_lookup
      -Wl,-install_name,@rpath/outlines_core_rs.cpython-313-darwin.so
      error: rustc 1.81.0 is not supported by the following packages:
        bincode@2.0.1 requires rustc 1.85.0
        bincode_derive@2.0.1 requires rustc 1.85.0
        icu_collections@2.0.0 requires rustc 1.82
        icu_locale_core@2.0.0 requires rustc 1.82
        icu_normalizer@2.0.0 requires rustc 1.82
        icu_normalizer_data@2.0.0 requires rustc 1.82
        icu_normalizer_data@2.0.0 requires rustc 1.82
        icu_normalizer_data@2.0.0 requires rustc 1.82
        icu_properties@2.0.1 requires rustc 1.82
        icu_properties_data@2.0.1 requires rustc 1.82
        icu_properties_data@2.0.1 requires rustc 1.82
        icu_properties_data@2.0.1 requires rustc 1.82
        icu_provider@2.0.0 requires rustc 1.82
        idna_adapter@1.2.1 requires rustc 1.82
        litemap@0.8.0 requires rustc 1.82
        zerotrie@0.2.2 requires rustc 1.82
        zerovec@0.11.2 requires rustc 1.82
      Either upgrade rustc or select compatible dependency versions with
      `cargo update <name>@<current-ver> --precise <compatible-ver>`
      where `<compatible-ver>` is the latest version supporting rustc 1.81.0

      error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path
      Cargo.toml --release -v --features 'pyo3/extension-module python-bindings'
      --crate-type cdylib -- --crate-type=cdylib -C 'link-args=-undefined dynamic_lookup
      -Wl,-install_name,@rpath/outlines_core_rs.cpython-313-darwin.so'` failed with code 101

      hint: This usually indicates a problem with the package or the build environment.
```